insert into GER_MOTIVO(EMPRESA,REVENDA,MOTIVO,DES_MOTIVO,TIPO_MOTIVO,REGISTRAR_CONCORRENTE)
 values (8.00,5.00,1.00,'COMPRA NA FABRICA','C',null);
insert into GER_MOTIVO(EMPRESA,REVENDA,MOTIVO,DES_MOTIVO,TIPO_MOTIVO,REGISTRAR_CONCORRENTE)
 values (8.00,5.00,2.00,'COMPRA DE TERCEIRO','T',null);
insert into GER_MOTIVO(EMPRESA,REVENDA,MOTIVO,DES_MOTIVO,TIPO_MOTIVO,REGISTRAR_CONCORRENTE)
 values (8.00,5.00,3.00,'RETORNO DEMONSTRACAO','D',null);
insert into GER_MOTIVO(EMPRESA,REVENDA,MOTIVO,DES_MOTIVO,TIPO_MOTIVO,REGISTRAR_CONCORRENTE)
 values (8.00,5.00,4.00,'ENTRADA CONSIGNACAO','T',null);
insert into GER_MOTIVO(EMPRESA,REVENDA,MOTIVO,DES_MOTIVO,TIPO_MOTIVO,REGISTRAR_CONCORRENTE)
 values (8.00,5.00,5.00,'SEM FUNDO','F',null);
insert into GER_MOTIVO(EMPRESA,REVENDA,MOTIVO,DES_MOTIVO,TIPO_MOTIVO,REGISTRAR_CONCORRENTE)
 values (8.00,5.00,10.00,'PRECO','P',null);
insert into GER_MOTIVO(EMPRESA,REVENDA,MOTIVO,DES_MOTIVO,TIPO_MOTIVO,REGISTRAR_CONCORRENTE)
 values (8.00,5.00,11.00,'ESTOQUE INDISPONIVEL','P',null);
insert into GER_MOTIVO(EMPRESA,REVENDA,MOTIVO,DES_MOTIVO,TIPO_MOTIVO,REGISTRAR_CONCORRENTE)
 values (8.00,5.00,12.00,'DESISTENCIA','S',null);
insert into GER_MOTIVO(EMPRESA,REVENDA,MOTIVO,DES_MOTIVO,TIPO_MOTIVO,REGISTRAR_CONCORRENTE)
 values (8.00,5.00,13.00,'PRECO ELEVADO','V',null);
insert into GER_MOTIVO(EMPRESA,REVENDA,MOTIVO,DES_MOTIVO,TIPO_MOTIVO,REGISTRAR_CONCORRENTE)
 values (8.00,5.00,14.00,'PRECO ELEVADO DE PECAS','P',null);
insert into GER_MOTIVO(EMPRESA,REVENDA,MOTIVO,DES_MOTIVO,TIPO_MOTIVO,REGISTRAR_CONCORRENTE)
 values (8.00,5.00,15.00,'FALTA DE ESTOQUE','V',null);
insert into GER_MOTIVO(EMPRESA,REVENDA,MOTIVO,DES_MOTIVO,TIPO_MOTIVO,REGISTRAR_CONCORRENTE)
 values (8.00,5.00,16.00,'COMPRA DE OUTRA MARCA','V',null);
insert into GER_MOTIVO(EMPRESA,REVENDA,MOTIVO,DES_MOTIVO,TIPO_MOTIVO,REGISTRAR_CONCORRENTE)
 values (8.00,5.00,17.00,'DESISTENCIA','V',null);
insert into GER_MOTIVO(EMPRESA,REVENDA,MOTIVO,DES_MOTIVO,TIPO_MOTIVO,REGISTRAR_CONCORRENTE)
 values (8.00,5.00,18.00,'REC. TRANSFERENCIA','T',null);
insert into GER_DEPARTAMENTO(EMPRESA,REVENDA,DEPARTAMENTO,NOME,IDENTIFICACAO,COBRA_TAXA,EXPEDICAO,NOME_ABREV,MODALIDADE,INATIVO_CONSULTAS)
 values (8.00,5.00,1.00,'VEICULOS NOVOS','V','N',null,'VN','V',null);
insert into GER_DEPARTAMENTO(EMPRESA,REVENDA,DEPARTAMENTO,NOME,IDENTIFICACAO,COBRA_TAXA,EXPEDICAO,NOME_ABREV,MODALIDADE,INATIVO_CONSULTAS)
 values (8.00,5.00,2.00,'VEICULOS USADOS','V','N',null,'VU','V',null);
insert into GER_DEPARTAMENTO(EMPRESA,REVENDA,DEPARTAMENTO,NOME,IDENTIFICACAO,COBRA_TAXA,EXPEDICAO,NOME_ABREV,MODALIDADE,INATIVO_CONSULTAS)
 values (8.00,5.00,3.00,'PECAS E ACESSORIOS','B','N',null,'PA','V',null);
insert into GER_DEPARTAMENTO(EMPRESA,REVENDA,DEPARTAMENTO,NOME,IDENTIFICACAO,COBRA_TAXA,EXPEDICAO,NOME_ABREV,MODALIDADE,INATIVO_CONSULTAS)
 values (8.00,5.00,4.00,'SERVICOS MEC/ELET.','O','N',null,'OFI','V',null);
insert into GER_DEPARTAMENTO(EMPRESA,REVENDA,DEPARTAMENTO,NOME,IDENTIFICACAO,COBRA_TAXA,EXPEDICAO,NOME_ABREV,MODALIDADE,INATIVO_CONSULTAS)
 values (8.00,5.00,5.00,'VENDA EXTERNA','V','N',null,null,'V',null);
insert into GER_DEPARTAMENTO(EMPRESA,REVENDA,DEPARTAMENTO,NOME,IDENTIFICACAO,COBRA_TAXA,EXPEDICAO,NOME_ABREV,MODALIDADE,INATIVO_CONSULTAS)
 values (8.00,5.00,6.00,'ADMINISTRACAO','A','N',null,'ADM','V',null);
insert into CTB_CENTRO_CUSTO(EMPRESA,REVENDA,CENTRO_CUSTO,CENTRO_SUPERIOR,DES_CENTRO_CUSTO,INATIVO_CONSULTAS)
 values (8.00,5.00,100.00,null,'VEICULOS NOVOS',null);
insert into CTB_CENTRO_CUSTO(EMPRESA,REVENDA,CENTRO_CUSTO,CENTRO_SUPERIOR,DES_CENTRO_CUSTO,INATIVO_CONSULTAS)
 values (8.00,5.00,200.00,null,'VEICULOS USADOS',null);
insert into CTB_CENTRO_CUSTO(EMPRESA,REVENDA,CENTRO_CUSTO,CENTRO_SUPERIOR,DES_CENTRO_CUSTO,INATIVO_CONSULTAS)
 values (8.00,5.00,300.00,null,'PECAS E ACESSORIOS',null);
insert into CTB_CENTRO_CUSTO(EMPRESA,REVENDA,CENTRO_CUSTO,CENTRO_SUPERIOR,DES_CENTRO_CUSTO,INATIVO_CONSULTAS)
 values (8.00,5.00,400.00,null,'MECANICA E ELETRICA',null);
insert into CTB_CENTRO_CUSTO(EMPRESA,REVENDA,CENTRO_CUSTO,CENTRO_SUPERIOR,DES_CENTRO_CUSTO,INATIVO_CONSULTAS)
 values (8.00,5.00,500.00,null,'VENDA EXTERNA',null);
insert into CTB_CENTRO_CUSTO(EMPRESA,REVENDA,CENTRO_CUSTO,CENTRO_SUPERIOR,DES_CENTRO_CUSTO,INATIVO_CONSULTAS)
 values (8.00,5.00,600.00,null,'ADMINISTRACAO',null);
insert into FIN_CAIXA(EMPRESA,REVENDA,CAIXA,DES_CAIXA,IMPRESSORA,OPERACIONAL)
 values (8.00,5.00,1.00,'CAIXA FINANCEIRO',null,'N');
insert into FIN_CAIXA(EMPRESA,REVENDA,CAIXA,DES_CAIXA,IMPRESSORA,OPERACIONAL)
 values (8.00,5.00,2.00,'CAIXA GERAL',null,'N');
insert into FIN_CAIXA(EMPRESA,REVENDA,CAIXA,DES_CAIXA,IMPRESSORA,OPERACIONAL)
 values (8.00,5.00,10.00,'CAIXA GARANTIA',null,'N');
insert into FIN_GRUPO(EMPRESA,REVENDA,GRUPO,DES_GRUPO)
 values (8.00,5.00,1.00,'ENTRADA');
insert into FIN_GRUPO(EMPRESA,REVENDA,GRUPO,DES_GRUPO)
 values (8.00,5.00,2.00,'SAIDA');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,1.00,'ENTRADA');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,2.00,'SAIDA');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,3.00,'DEPOSITO');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,4.00,'DEP.CHEQUE');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,5.00,'TED/DOC');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,6.00,'FINANCIAMENTO');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,7.00,'TRASNF. CONTA');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,8.00,'CHEQUE COMPENSADO');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,9.00,'LIBERACAO GARANTIDA');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,11.00,'ESTORNO DE ENTRADA');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,12.00,'ESTORNO DE SAIDA');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,13.00,'CARTAO DEB/CRED');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,14.00,'PG FLOOR PLAN');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,15.00,'FUNDO GARANTIDOR');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,16.00,'DEV. CHEQUE');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,17.00,'FOMENTO CHEQUE');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,18.00,'RECEB. TITULOS');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,20.00,'CPMF');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,21.00,'IOF');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,22.00,'TARIFAS');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,23.00,'PAGTO DE TITULOS');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,24.00,'LIQ. PECAS');
insert into FIN_TRANSACAO(EMPRESA,REVENDA,TRANSACAO,DES_TRANSACAO)
 values (8.00,5.00,25.00,'CREDITO GARANTIA');
insert into OFI_CATEGORIA_OS(EMPRESA,REVENDA,CATEGORIA_OS,DES_CATEGORIA,VLR_AUTORIZACAO,CONTRATO_REC_DES)
 values (8.00,5.00,1.00,'EXTERNA',null,null);
insert into OFI_CATEGORIA_OS(EMPRESA,REVENDA,CATEGORIA_OS,DES_CATEGORIA,VLR_AUTORIZACAO,CONTRATO_REC_DES)
 values (8.00,5.00,2.00,'GARANTIA',null,null);
insert into OFI_CATEGORIA_OS(EMPRESA,REVENDA,CATEGORIA_OS,DES_CATEGORIA,VLR_AUTORIZACAO,CONTRATO_REC_DES)
 values (8.00,5.00,3.00,'REVISAO',null,null);
insert into OFI_CATEGORIA_OS(EMPRESA,REVENDA,CATEGORIA_OS,DES_CATEGORIA,VLR_AUTORIZACAO,CONTRATO_REC_DES)
 values (8.00,5.00,4.00,'INTERNA',null,null);
insert into OFI_HORARIO_RECEPCAO(EMPRESA,REVENDA,HORARIO_RECEPCAO,DES_HORARIO,HORA_INICIO,HORA_FIM,TEMPO_ATENDIMENTO,INTERVALO1_INI,INTERVALO1_FIM,INTERVALO2_INI,INTERVALO2_FIM,INTERVALO3_INI,INTERVALO3_FIM)
 values (8.00,5.00,1.00,'RECEPCAO',TO_DATE('30/12/1899 08:00:00','dd/mm/yyyy HH24:MI:SS'),TO_DATE('30/12/1899 11:00:00','dd/mm/yyyy HH24:MI:SS'),TO_DATE('30/12/1899 00:15:00','dd/mm/yyyy HH24:MI:SS'),TO_DATE('30/12/1899 11:00:00','dd/mm/yyyy HH24:MI:SS'),TO_DATE('30/12/1899 13:00:00','dd/mm/yyyy HH24:MI:SS'),null,null,null,null);
insert into OFI_HORARIO_MECANICO(EMPRESA,REVENDA,HORARIO_OFICINA,INICIO_TURNO1,FINAL_TURNO1,INICIO_TURNO2,FINAL_TURNO2,DES_HORARIO,INICIO_INTERVALO1,FINAL_INTERVALO1,INICIO_INTERVALO2,FINAL_INTERVALO2)
 values (8.00,5.00,1.00,TO_DATE('30/12/1899 08:00:00','dd/mm/yyyy HH24:MI:SS'),TO_DATE('30/12/1899 11:00:00','dd/mm/yyyy HH24:MI:SS'),TO_DATE('30/12/1899 13:00:00','dd/mm/yyyy HH24:MI:SS'),TO_DATE('30/12/1899 18:00:00','dd/mm/yyyy HH24:MI:SS'),'SEMANA',null,null,null,null);
insert into OFI_HORARIO_MECANICO(EMPRESA,REVENDA,HORARIO_OFICINA,INICIO_TURNO1,FINAL_TURNO1,INICIO_TURNO2,FINAL_TURNO2,DES_HORARIO,INICIO_INTERVALO1,FINAL_INTERVALO1,INICIO_INTERVALO2,FINAL_INTERVALO2)
 values (8.00,5.00,2.00,TO_DATE('30/12/1899 08:00:00','dd/mm/yyyy HH24:MI:SS'),TO_DATE('30/12/1899 12:00:00','dd/mm/yyyy HH24:MI:SS'),TO_DATE('30/12/1899 00:00:00','dd/mm/yyyy HH24:MI:SS'),TO_DATE('30/12/1899 00:00:00','dd/mm/yyyy HH24:MI:SS'),'SABADO',null,null,null,null);
insert into OFI_SECAO(EMPRESA,REVENDA,SECAO_OFICINA,DES_SECAO,IDENTIFICACAO,PERCENTUAL_TEMPO,MOSTRARNATORRE,ABREVIATURA_SECAO)
 values (8.00,5.00,1.00,'MECANICA','M',0.00,null,null);
insert into OFI_TIPO_SERVICO(EMPRESA,REVENDA,TIPO_SERVICO,DES_TIPO_SERVICO,PRODUTIVO,TIPO_SERVICO_OS,PERMITIR_APONTAMENTO,PERMITIR_CCC)
 values (8.00,5.00,'EX','EXTERNA','S','E','S','N');
insert into OFI_TIPO_SERVICO(EMPRESA,REVENDA,TIPO_SERVICO,DES_TIPO_SERVICO,PRODUTIVO,TIPO_SERVICO_OS,PERMITIR_APONTAMENTO,PERMITIR_CCC)
 values (8.00,5.00,'GA','GARANTIA','S','G',null,'N');
insert into OFI_TIPO_SERVICO(EMPRESA,REVENDA,TIPO_SERVICO,DES_TIPO_SERVICO,PRODUTIVO,TIPO_SERVICO_OS,PERMITIR_APONTAMENTO,PERMITIR_CCC)
 values (8.00,5.00,'IN','INTERNA','S','I',null,'N');
insert into OFI_TIPO_SERVICO(EMPRESA,REVENDA,TIPO_SERVICO,DES_TIPO_SERVICO,PRODUTIVO,TIPO_SERVICO_OS,PERMITIR_APONTAMENTO,PERMITIR_CCC)
 values (8.00,5.00,'RE','REVISAO','S','R','S','N');
insert into OFI_PARAMETRO(EMPRESA,REVENDA,TIPO_OS,SERVICO_INTERNO,HORA_EMISSAO,GRAVA_NRO_ROMANEIO,IMPRIME_CUPOM,POLITICA_PADRAO,FABRICANTE,FAB_DEBITO_REVISAO_HONDA,FAB_GARANTIA,CLIENTE_OS_INTERNA,OBS_ORCAMENTO,TIPO_TRANSACAO_INT,TIPO_TRANSACAO_EXT,TIPO_TRANSACAO_GAR,TIPO_TRANSACAO_REC_GAR,TIPO_TRANSACAO_ENV_GAR,NRO_DIAS_ORCAMENTO,PERMITE_NEGOCIAR_INT,PERMITE_NEGOCIAR_EXT,PERMITE_NEGOCIAR_GAR,PERMITE_NEGOCIAR_REV,CONDICAO_NAO_NEGOCIAVEL,TIPO_IMPRESSAO_ORC,FORMA_CONTATO,TIPO_CONTATO,SUB_TIPO_CONTATO,SEPARAR_ITENS_REVISAO,ORIGEM_TRAFEGO,BASE_PRECO_GAR,PER_PRECO_GAR,TIPO_AGENDAMENTO,APONTAMENTO_MECANICO,LANCAR_ITEM_OS,SERVICO_QTD_ZERADA,IMPRIME_COD_PECA,IMPRIME_COD_MAODEOBRA,QTD_TEMPOS,VAL_TEMPOS,TIPO_SERVICO_AR,POLITICA_PADRAO_AR,NRO_AUTOMATICO_OS,DESCONTO_CFE_GRUPO,TIPO_SERVICO_UNICO,TRANSACAO_REM_CAMPO,IMPRIME_NF_SEPARADA,CUSTO_MAODEOBRA,BLOQUEAR_REQ_PECA_GAR,IMP_ICMS_NFGARANTIA,MULTIPLO_AGENDAMENTO,CATEGORIA_OS_SERVRAPIDO,DESCRICAO_NF_FRANQUIA,AUTORIZAR_OS_GARANTIA,USUARIO_NOTIFICACAO,APONTAR_SERVICO_QTD_ZERADA,CATEGORIA_PADRAO_OS_EXT,CATEGORIA_PADRAO_OS_INT,CATEGORIA_PADRAO_OS_GAR,CATEGORIA_PADRAO_OS_REV,SERVICO_DESPESA,CALCULAR_FRANQUIA_DESCONTO,NF_SEGURO_CLIENTE,SERVICO_NF_FRANQUIA,IMP_NFPRESTSERV,IMP_NFENTSERV,EMITIR_NFDESCLIVR_GARANTIA,TIPO_TRANSACAO_NFDESCLGAR,CONDPAG_NFDESCLGAR,BLOQUEAR_OS_MECANICO,DIAS_VALIDADE_ATENDIMENTO,BLOQUEAR_TELA_ATENDIMENTO,BLOQUEAR_CLIENTE_SEM_CREDITO,BLOQUEAR_PF_SEM_PASSAGEM,BLOQUEAR_PJ_SEM_PASSAGEM,AUTORIZAR_ORCAMENTO,AUTORIZAR_ABRIR_OS_EXT,AUTORIZAR_ABRIR_OS_INT,AUTORIZAR_ABRIR_OS_GAR,AUTORIZAR_ABRIR_OS_REV,CONSISTE_DEPTO_DEBITO_INTERNO,DEVOLUCAO_PECAS_MEC_DIF,USA_OS_ESP_TOYOTA,CONTROLA_NFDESPESA,SERVICO_TERCEIROS,SERVICO_DESLOCAMENTO,SERVICO_KM_RODADO,NF_GARANTIA_SEPARADA,TIPO_PRE_OS,FECHAR_SERVICO_GARANTIA,INFORMAR_LOCAL_SERVICO,INFORMAR_PRIORIDADE_OFICINA,CONFIRMAR_KM,HORAS_TRABALHADA_DIA,IMP_NF_VEICULOS_OS,TIPO_TRANSACAO_NFEV,TIPO_TRANSACAO_NFSV,CODIGO_TRIBUTACAO_NFEV,CODIGO_TRIBUTACAO_NFSV,CODIGO_CFOP_NFEV,CODIGO_CFOP_NFSV,COND_PAGTO_NFEV,COND_PAGTO_NFSV,CONSIDERAR_SERVICO_TORRE)
 values (8.00,5.00,60.00,'N','N','S','N',1.00,8054.00,null,null,7813.00,null,'T26','S22','G26','G22','G23',null,'N','S','S','S',99.00,'T',3.00,10.00,1.00,'N',1.00,'G',10.00,'C','N','N','S','S',null,null,null,'EX',1.00,'S','N','N','S1','N',25.00,'N','S','N',1.00,null,'S',222.00,'N',1.00,4.00,2.00,3.00,null,'N','N',null,null,null,'S','G25',99.00,'N',null,null,null,null,null,null,null,null,null,null,'S',null,null,null,null,null,null,null,null,'S',null,null,'N',null,null,null,null,null,null,null,null,null,null,'C');
insert into PEC_PARAMETRO(EMPRESA,REVENDA,VENDA_PERDIDA,AGRUPAMENTO,TIPO_TRANSACAO,VAL_PECA_1,VAL_PECA_3,FRACAO_0_1,FRACAO_1_2,CONTROLA_ROMANEIO,OBS_ORCAMENTO,RENTABILIDADE,RENTABILIDADE_ATACADO,ICMS_CUSTO_REPOSICAO,PEDE_CODTRIBUTACAO,VALOR_MEIO_TURNO,TIPO_CONTATO,SUB_TIPO_CONTATO,ORIGEM_TRAFEGO,FORMA_CONTATO,PCT_POLITICA_1,PCT_POLITICA_2,PCT_POLITICA_3,PCT_POLITICA_4,HIFEN_CODIGO_BARRAS,PARA_BASE_ICMS_RETIDO,CATEGORIA_PECAS_ST,CONTROLE_RECEBIMENTO_COMPRA,VLR_TOLERANCIA_COMPRA,VALORIZACAO_PEDIDO,INFORMAR_MOTIVO_NFENTRADA,MOSTRAR_PERCENTUAL_DESCONTO,TIPO_VISUALIZACAO_DESCONTO,ZEROS_ESQUERDA,TIPO_AVISO_RECEBIMENTO,COMPROMETE_ITEM_PENDENTE,VALIDA_FORNECEDOR_PEDIDO,DIAS_VALIDADE_ATENDIMENTO,BLOQUEAR_TELA_ATENDIMENTO,TRANSACOES_NAO_MOVIMENTA,USA_POLITICA_PADRAO,CONSISTE_DESC_LOTE,OBRIGAR_ANO_KIT,OBRIGAR_NFORIGEM,CLIENTE_VENDA_PERDIDA,DES_POLITICA_1,DES_POLITICA_2,DES_POLITICA_3,DES_POLITICA_4,BLOQUEAR_CLIENTE_SEM_CREDITO,CONSIDERAR_FRETE_DEST_RENT,DESPESA_ENTRADA_PECAS_VEI,REGISTRAR_VP_REMOVER_ITEM,REGISTRAR_VENDA_PERDIDA_AUTO,MOTIVO_INDISPONIVEL,MOTIVO_PRECO_ELEVADO)
 values (8.00,5.00,'S','G','P26',100.00,30.00,49999.00,50000.00,null,null,5.00,0.00,null,'S',0.00,10.00,1.00,1.00,2.00,15.00,null,null,null,'N','V',5.00,null,null,'R','S','S','V',null,'U',null,null,null,null,null,null,null,null,null,7813.00,'OVERPRIZE DAFRA',null,null,null,'N','N',null,null,null,null,null);
